PRAGMA foreign_keys = ON;

-- ============================================================================
-- Kimujo Holdings Limited: Property Management and Revenue Collection Schema
-- SQLite-compatible DDL only. Populate data via scripts/import_kimujo_real_data.py.
-- Primary keys are generated by SQLite. No INSERT statement supplies an ID.
-- This script intentionally has no BEGIN/COMMIT wrapper because many SQLite
-- execution tools already run scripts inside a transaction. When running from
-- a raw SQLite connection, the calling application should own the transaction.
-- ============================================================================

-- Dependency-safe teardown.
DROP VIEW IF EXISTS v_tenant_input;
DROP VIEW IF EXISTS v_current_tenant_directory;
DROP VIEW IF EXISTS v_tenant_account_status;

DROP TRIGGER IF EXISTS tr_security_deposit_payment_immutable_delete;
DROP TRIGGER IF EXISTS tr_security_deposit_payment_immutable_update;
DROP TRIGGER IF EXISTS tr_security_deposit_payment_apply;
DROP TRIGGER IF EXISTS tr_security_deposit_payment_validate;
DROP TRIGGER IF EXISTS tr_payment_allocation_immutable_delete;
DROP TRIGGER IF EXISTS tr_payment_allocation_immutable_update;
DROP TRIGGER IF EXISTS tr_payment_allocation_apply;
DROP TRIGGER IF EXISTS tr_payment_allocation_validate;

DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS security_deposit_payments;
DROP TABLE IF EXISTS payment_allocations;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS rent_obligations;
DROP TABLE IF EXISTS security_deposits;
DROP TABLE IF EXISTS tenancy_assignments;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS tenants;
DROP TABLE IF EXISTS estates;

-- ============================================================================
-- Master entities
-- ============================================================================

CREATE TABLE estates (
    estate_id       INTEGER PRIMARY KEY,
    estate_code     TEXT NOT NULL UNIQUE,
    estate_name     TEXT NOT NULL UNIQUE,
    is_active       INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (estate_code = upper(trim(estate_code))),
    CHECK (estate_name = trim(estate_name))
);

CREATE TABLE units (
    unit_id                 INTEGER PRIMARY KEY,
    estate_id               INTEGER NOT NULL,
    unit_number             TEXT NOT NULL,
    listed_monthly_rent     INTEGER NOT NULL
                            CHECK (listed_monthly_rent BETWEEN 100000 AND 15000000),
    is_active               INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at              TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (estate_id)
        REFERENCES estates(estate_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    UNIQUE (estate_id, unit_number),
    CHECK (unit_number = upper(trim(unit_number))),
    CHECK (length(unit_number) >= 2)
);

CREATE TABLE tenants (
    -- Omit tenant_id from INSERT statements; SQLite generates it automatically.
    tenant_id       INTEGER PRIMARY KEY,
    tenant_type     TEXT NOT NULL DEFAULT 'INDIVIDUAL'
                    CHECK (tenant_type IN ('INDIVIDUAL', 'BUSINESS')),
    business_name   TEXT,
    first_name      TEXT NOT NULL,
    middle_name     TEXT,
    last_name       TEXT NOT NULL,
    phone_number    TEXT NOT NULL UNIQUE,
    national_id_number TEXT UNIQUE,
    alt_phone_number TEXT,
    notes           TEXT NOT NULL DEFAULT 'No notes.',
    is_active       INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (
        tenant_type <> 'BUSINESS'
        OR (business_name IS NOT NULL AND trim(business_name) <> '')
    ),
    -- Application code should perform complete Unicode-aware title-casing
    -- before insert/update. These checks protect standard ASCII name input.
    CHECK (
        first_name = trim(first_name)
        AND first_name = upper(substr(first_name, 1, 1)) || lower(substr(first_name, 2))
    ),
    CHECK (
        middle_name IS NULL
        OR (
            middle_name = trim(middle_name)
            AND middle_name = upper(substr(middle_name, 1, 1)) || lower(substr(middle_name, 2))
        )
    ),
    CHECK (
        last_name = trim(last_name)
        AND last_name = upper(substr(last_name, 1, 1)) || lower(substr(last_name, 2))
    ),

    -- Seed phone format: +256 followed by a 9-digit mobile number.
    CHECK (phone_number GLOB '+2567[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
);

-- Allows tenancy history while partial unique indexes permit only one active
-- tenancy per tenant and per unit.
CREATE TABLE tenancy_assignments (
    tenancy_id              INTEGER PRIMARY KEY,
    tenant_id               INTEGER NOT NULL,
    unit_id                 INTEGER NOT NULL,
    start_date              TEXT NOT NULL,
    end_date                TEXT,
    scheduled_move_out_date TEXT,
    agreed_monthly_rent     INTEGER NOT NULL
                            CHECK (agreed_monthly_rent BETWEEN 100000 AND 15000000),
    rent_due_day            INTEGER NOT NULL DEFAULT 1 CHECK (rent_due_day BETWEEN 1 AND 31),
    grace_period_days       INTEGER NOT NULL DEFAULT 5 CHECK (grace_period_days BETWEEN 0 AND 31),
    is_primary              INTEGER NOT NULL DEFAULT 1 CHECK (is_primary IN (0, 1)),
    created_at              TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id)
        REFERENCES tenants(tenant_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    FOREIGN KEY (unit_id)
        REFERENCES units(unit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CHECK (start_date GLOB '????-??-??'),
    CHECK (end_date IS NULL OR end_date GLOB '????-??-??'),
    CHECK (scheduled_move_out_date IS NULL OR scheduled_move_out_date GLOB '????-??-??'),
    CHECK (end_date IS NULL OR end_date >= start_date)
);

-- ============================================================================
-- Financial ledger entities
-- ============================================================================

CREATE TABLE security_deposits (
    security_deposit_id      INTEGER PRIMARY KEY,
    tenancy_id               INTEGER NOT NULL UNIQUE,
    expected_amount          INTEGER NOT NULL CHECK (expected_amount > 0),
    received_amount          INTEGER NOT NULL DEFAULT 0
                            CHECK (received_amount >= 0 AND received_amount <= expected_amount),
    status                   TEXT NOT NULL DEFAULT 'UNPAID'
                            CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID')),
    created_at               TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenancy_id)
        REFERENCES tenancy_assignments(tenancy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CHECK (
        (status = 'UNPAID' AND received_amount = 0)
        OR (status = 'PARTIAL' AND received_amount > 0 AND received_amount < expected_amount)
        OR (status = 'PAID' AND received_amount = expected_amount)
    )
);

CREATE TABLE rent_obligations (
    rent_obligation_id        INTEGER PRIMARY KEY,
    tenancy_id                INTEGER NOT NULL,
    rent_month                TEXT NOT NULL,
    due_date                  TEXT NOT NULL,
    amount_due                INTEGER NOT NULL CHECK (amount_due > 0),
    allocated_amount          INTEGER NOT NULL DEFAULT 0
                              CHECK (allocated_amount >= 0 AND allocated_amount <= amount_due),
    status                    TEXT NOT NULL DEFAULT 'UNPAID'
                              CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID')),
    created_at                TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenancy_id)
        REFERENCES tenancy_assignments(tenancy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    UNIQUE (tenancy_id, rent_month),
    CHECK (rent_month GLOB '????-??'),
    CHECK (due_date GLOB '????-??-??'),
    CHECK (
        (status = 'UNPAID' AND allocated_amount = 0)
        OR (status = 'PARTIAL' AND allocated_amount > 0 AND allocated_amount < amount_due)
        OR (status = 'PAID' AND allocated_amount = amount_due)
    )
);

CREATE TABLE payments (
    payment_id              INTEGER PRIMARY KEY,
    tenant_id               INTEGER NOT NULL,
    payment_reference       TEXT NOT NULL UNIQUE,
    payment_type            TEXT NOT NULL
                            CHECK (payment_type IN ('RENT', 'SECURITY_DEPOSIT', 'MIXED', 'ADJUSTMENT')),
    amount                  INTEGER NOT NULL CHECK (amount > 0),
    payment_date            TEXT NOT NULL,
    payment_method          TEXT NOT NULL
                            CHECK (payment_method IN ('MOBILE_MONEY', 'BANK_TRANSFER', 'CASH')),
    payment_status          TEXT NOT NULL DEFAULT 'POSTED'
                            CHECK (payment_status IN ('POSTED', 'VOIDED', 'REVERSED')),
    created_at              TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id)
        REFERENCES tenants(tenant_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CHECK (payment_date GLOB '????-??-??')
);

CREATE TABLE payment_allocations (
    payment_allocation_id   INTEGER PRIMARY KEY,
    payment_id              INTEGER NOT NULL,
    rent_obligation_id      INTEGER NOT NULL,
    allocated_amount        INTEGER NOT NULL CHECK (allocated_amount > 0),
    created_at              TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    FOREIGN KEY (rent_obligation_id)
        REFERENCES rent_obligations(rent_obligation_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    UNIQUE (payment_id, rent_obligation_id)
);

CREATE TABLE security_deposit_payments (
    security_deposit_payment_id  INTEGER PRIMARY KEY,
    security_deposit_id          INTEGER NOT NULL,
    payment_id                   INTEGER NOT NULL UNIQUE,
    allocated_amount             INTEGER NOT NULL CHECK (allocated_amount > 0),
    created_at                   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (security_deposit_id)
        REFERENCES security_deposits(security_deposit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    UNIQUE (security_deposit_id, payment_id)
);

CREATE TABLE receipts (
    receipt_id              INTEGER PRIMARY KEY,
    payment_id              INTEGER NOT NULL UNIQUE,
    receipt_number          TEXT NOT NULL UNIQUE,
    issued_at               TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    issued_by               TEXT NOT NULL DEFAULT 'SYSTEM',
    balance_after           INTEGER NOT NULL DEFAULT 0 CHECK (balance_after >= 0),

    FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CHECK (
        length(receipt_number) > 0
        AND receipt_number NOT GLOB '*[^0-9]*'
    )
);

-- ============================================================================
-- Lookup and reporting indexes
-- ============================================================================

CREATE INDEX idx_estates_name
    ON estates(estate_name);

CREATE INDEX idx_tenants_phone_number
    ON tenants(phone_number);

CREATE INDEX idx_tenancy_assignments_tenant_unit
    ON tenancy_assignments(tenant_id, unit_id, end_date);

CREATE UNIQUE INDEX ux_active_tenancy_per_tenant
    ON tenancy_assignments(tenant_id)
    WHERE end_date IS NULL;

CREATE UNIQUE INDEX ux_active_tenancy_per_unit
    ON tenancy_assignments(unit_id)
    WHERE end_date IS NULL;

CREATE INDEX idx_rent_obligations_status
    ON rent_obligations(status, due_date);

CREATE INDEX idx_payments_payment_date
    ON payments(payment_date);

CREATE INDEX idx_receipts_receipt_number
    ON receipts(receipt_number);

-- ============================================================================
-- Ledger integrity triggers
-- ============================================================================

CREATE TRIGGER tr_payment_allocation_validate
BEFORE INSERT ON payment_allocations
BEGIN
    SELECT CASE
        WHEN (SELECT payment_status FROM payments WHERE payment_id = NEW.payment_id) <> 'POSTED'
        THEN RAISE(ABORT, 'Only posted payments may be allocated to rent obligations')
    END;

    SELECT CASE
        WHEN (SELECT payment_type FROM payments WHERE payment_id = NEW.payment_id)
             NOT IN ('RENT', 'MIXED')
        THEN RAISE(ABORT, 'Only RENT or MIXED payments may be allocated to rent obligations')
    END;

    SELECT CASE
        WHEN (SELECT tenant_id FROM payments WHERE payment_id = NEW.payment_id) <>
             (
                 SELECT ta.tenant_id
                 FROM rent_obligations ro
                 JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
                 WHERE ro.rent_obligation_id = NEW.rent_obligation_id
             )
        THEN RAISE(ABORT, 'Payment tenant does not match rent obligation tenant')
    END;

    SELECT CASE
        WHEN NEW.allocated_amount >
             (
                 SELECT amount - COALESCE(
                     (
                         SELECT SUM(allocated_amount)
                         FROM payment_allocations
                         WHERE payment_id = NEW.payment_id
                     ),
                     0
                 )
                 FROM payments
                 WHERE payment_id = NEW.payment_id
             )
        THEN RAISE(ABORT, 'Payment allocation exceeds available payment balance')
    END;

    SELECT CASE
        WHEN NEW.allocated_amount >
             (
                 SELECT amount_due - allocated_amount
                 FROM rent_obligations
                 WHERE rent_obligation_id = NEW.rent_obligation_id
             )
        THEN RAISE(ABORT, 'Payment allocation exceeds outstanding rent balance')
    END;
END;

CREATE TRIGGER tr_payment_allocation_apply
AFTER INSERT ON payment_allocations
BEGIN
    UPDATE rent_obligations
    SET
        allocated_amount = (
            SELECT COALESCE(SUM(pa.allocated_amount), 0)
            FROM payment_allocations pa
            WHERE pa.rent_obligation_id = NEW.rent_obligation_id
        ),
        status = CASE
            WHEN (
                SELECT COALESCE(SUM(pa.allocated_amount), 0)
                FROM payment_allocations pa
                WHERE pa.rent_obligation_id = NEW.rent_obligation_id
            ) = 0 THEN 'UNPAID'
            WHEN (
                SELECT COALESCE(SUM(pa.allocated_amount), 0)
                FROM payment_allocations pa
                WHERE pa.rent_obligation_id = NEW.rent_obligation_id
            ) < amount_due THEN 'PARTIAL'
            ELSE 'PAID'
        END
    WHERE rent_obligation_id = NEW.rent_obligation_id;
END;

-- The allocation ledger is immutable. Correct errors using an adjustment.
CREATE TRIGGER tr_payment_allocation_immutable_update
BEFORE UPDATE ON payment_allocations
BEGIN
    SELECT RAISE(ABORT, 'Payment allocations are immutable; post an adjustment instead');
END;

CREATE TRIGGER tr_payment_allocation_immutable_delete
BEFORE DELETE ON payment_allocations
BEGIN
    SELECT RAISE(ABORT, 'Payment allocations are immutable; post an adjustment instead');
END;

CREATE TRIGGER tr_security_deposit_payment_validate
BEFORE INSERT ON security_deposit_payments
BEGIN
    SELECT CASE
        WHEN (SELECT payment_status FROM payments WHERE payment_id = NEW.payment_id) <> 'POSTED'
        THEN RAISE(ABORT, 'Only posted payments may be allocated to security deposits')
    END;

    SELECT CASE
        WHEN (SELECT payment_type FROM payments WHERE payment_id = NEW.payment_id)
             NOT IN ('SECURITY_DEPOSIT', 'MIXED')
        THEN RAISE(ABORT, 'Payment type cannot be allocated to security deposit')
    END;

    SELECT CASE
        WHEN (SELECT tenant_id FROM payments WHERE payment_id = NEW.payment_id) <>
             (
                 SELECT ta.tenant_id
                 FROM security_deposits sd
                 JOIN tenancy_assignments ta ON ta.tenancy_id = sd.tenancy_id
                 WHERE sd.security_deposit_id = NEW.security_deposit_id
             )
        THEN RAISE(ABORT, 'Payment tenant does not match security deposit tenant')
    END;

    SELECT CASE
        WHEN NEW.allocated_amount >
             (
                 SELECT amount - COALESCE(
                     (
                         SELECT SUM(allocated_amount)
                         FROM security_deposit_payments
                         WHERE payment_id = NEW.payment_id
                     ),
                     0
                 )
                 FROM payments
                 WHERE payment_id = NEW.payment_id
             )
        THEN RAISE(ABORT, 'Security deposit allocation exceeds payment balance')
    END;

    SELECT CASE
        WHEN NEW.allocated_amount >
             (
                 SELECT expected_amount - received_amount
                 FROM security_deposits
                 WHERE security_deposit_id = NEW.security_deposit_id
             )
        THEN RAISE(ABORT, 'Security deposit allocation exceeds outstanding balance')
    END;
END;

CREATE TRIGGER tr_security_deposit_payment_apply
AFTER INSERT ON security_deposit_payments
BEGIN
    UPDATE security_deposits
    SET
        received_amount = (
            SELECT COALESCE(SUM(sdp.allocated_amount), 0)
            FROM security_deposit_payments sdp
            WHERE sdp.security_deposit_id = NEW.security_deposit_id
        ),
        status = CASE
            WHEN (
                SELECT COALESCE(SUM(sdp.allocated_amount), 0)
                FROM security_deposit_payments sdp
                WHERE sdp.security_deposit_id = NEW.security_deposit_id
            ) = 0 THEN 'UNPAID'
            WHEN (
                SELECT COALESCE(SUM(sdp.allocated_amount), 0)
                FROM security_deposit_payments sdp
                WHERE sdp.security_deposit_id = NEW.security_deposit_id
            ) < expected_amount THEN 'PARTIAL'
            ELSE 'PAID'
        END
    WHERE security_deposit_id = NEW.security_deposit_id;
END;

CREATE TRIGGER tr_security_deposit_payment_immutable_update
BEFORE UPDATE ON security_deposit_payments
BEGIN
    SELECT RAISE(ABORT, 'Security deposit allocations are immutable; post an adjustment instead');
END;

CREATE TRIGGER tr_security_deposit_payment_immutable_delete
BEFORE DELETE ON security_deposit_payments
BEGIN
    SELECT RAISE(ABORT, 'Security deposit allocations are immutable; post an adjustment instead');
END;

-- ============================================================================
-- Controlled tenant input interface
-- ============================================================================
-- Use this view for ordinary inserts to normalize simple ASCII name casing.
-- Production application code should still use Unicode-aware title-case logic.

CREATE VIEW v_tenant_input AS
SELECT
    first_name,
    middle_name,
    last_name,
    phone_number,
    national_id_number,
    alt_phone_number,
    notes
FROM tenants;

CREATE TRIGGER tr_v_tenant_input_normalize_insert
INSTEAD OF INSERT ON v_tenant_input
BEGIN
    INSERT INTO tenants (
        first_name,
        middle_name,
        last_name,
        phone_number,
        national_id_number,
        alt_phone_number,
        notes
    )
    VALUES (
        upper(substr(trim(NEW.first_name), 1, 1)) || lower(substr(trim(NEW.first_name), 2)),
        CASE
            WHEN NULLIF(trim(NEW.middle_name), '') IS NULL THEN NULL
            ELSE upper(substr(trim(NEW.middle_name), 1, 1)) || lower(substr(trim(NEW.middle_name), 2))
        END,
        upper(substr(trim(NEW.last_name), 1, 1)) || lower(substr(trim(NEW.last_name), 2)),
        trim(NEW.phone_number),
        NULLIF(upper(trim(NEW.national_id_number)), ''),
        NULLIF(trim(NEW.alt_phone_number), ''),
        COALESCE(NULLIF(trim(NEW.notes), ''), 'No notes.')
    );
END;

-- ============================================================================
-- Reporting views
-- ============================================================================

CREATE VIEW v_current_tenant_directory AS
SELECT
    t.tenant_id,
    t.tenant_type,
    t.business_name,
    t.first_name,
    t.middle_name,
    t.last_name,
    CASE
        WHEN t.tenant_type = 'BUSINESS' AND trim(t.business_name) <> ''
            THEN trim(t.business_name)
        ELSE trim(t.first_name || ' ' || COALESCE(t.middle_name || ' ', '') || t.last_name)
    END AS tenant_name,
    t.phone_number,
    t.alt_phone_number,
    t.notes,
    e.estate_id,
    e.estate_name,
    u.unit_id,
    u.unit_number AS house_number,
    ta.tenancy_id,
    ta.agreed_monthly_rent AS expected_monthly_rent,
    ta.rent_due_day,
    ta.grace_period_days,
    ta.start_date,
    ta.end_date,
    ta.scheduled_move_out_date,
    sd.security_deposit_id,
    sd.status AS security_deposit_status,
    sd.expected_amount AS security_deposit_expected,
    sd.received_amount AS security_deposit_received
FROM tenants t
JOIN tenancy_assignments ta
    ON ta.tenant_id = t.tenant_id
   AND ta.end_date IS NULL
JOIN units u
    ON u.unit_id = ta.unit_id
JOIN estates e
    ON e.estate_id = u.estate_id
JOIN security_deposits sd
    ON sd.tenancy_id = ta.tenancy_id;

CREATE VIEW v_tenant_account_status AS
SELECT
    d.*,
    COALESCE((
        SELECT COUNT(*)
        FROM rent_obligations ro
        JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
        WHERE ta.tenant_id = d.tenant_id
          AND ta.end_date IS NULL
          AND ro.rent_month >= '2025-12'
          AND ro.rent_month <= strftime('%Y-%m', 'now')
          AND ro.status <> 'PAID'
    ), 0) AS pending_months_owed,
    COALESCE((
        SELECT SUM(ro.amount_due - ro.allocated_amount)
        FROM rent_obligations ro
        JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
        WHERE ta.tenant_id = d.tenant_id
          AND ta.end_date IS NULL
          AND ro.rent_month >= '2025-12'
          AND ro.rent_month <= strftime('%Y-%m', 'now')
    ), 0) AS rent_outstanding_balance,
    d.security_deposit_expected - d.security_deposit_received AS security_deposit_balance,
    CASE
        WHEN d.security_deposit_status <> 'PAID'
             AND COALESCE((
                 SELECT COUNT(*)
                 FROM rent_obligations ro
                 JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
                 WHERE ta.tenant_id = d.tenant_id
                   AND ta.end_date IS NULL
                   AND ro.rent_month >= '2025-12'
                   AND ro.rent_month <= strftime('%Y-%m', 'now')
                   AND ro.status <> 'PAID'
             ), 0) = 0
        THEN 'MISSING_SECURITY_DEPOSIT'

        WHEN COALESCE((
            SELECT COUNT(*)
            FROM rent_obligations ro
            JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
            WHERE ta.tenant_id = d.tenant_id
              AND ta.end_date IS NULL
              AND ro.rent_month >= '2025-12'
              AND ro.rent_month <= strftime('%Y-%m', 'now')
              AND ro.status <> 'PAID'
        ), 0) > 0
        THEN 'IN_ARREARS'

        WHEN d.start_date >= date('now', '-90 days')
        THEN 'NEW_MOVE_IN_CLEAN'

        ELSE 'FULLY_PAID_UP'
    END AS account_category
FROM v_current_tenant_directory d;
