PRAGMA foreign_keys = ON;

-- ============================================================================
-- Kimujo Holdings Limited: Property Management and Revenue Collection Schema
-- SQLite-compatible DDL and deterministic application seed data.
-- Primary keys are generated by SQLite. No INSERT statement supplies an ID.
-- This script intentionally has no BEGIN/COMMIT wrapper because many SQLite
-- execution tools already run scripts inside a transaction. When running from
-- a raw SQLite connection, the calling application should own the transaction.
-- ============================================================================

-- Dependency-safe teardown.
DROP VIEW IF EXISTS v_tenant_input;
DROP VIEW IF EXISTS v_current_tenant_directory;
DROP VIEW IF EXISTS v_tenant_account_status;

DROP TRIGGER IF EXISTS tr_security_deposit_payment_immutable_delete;
DROP TRIGGER IF EXISTS tr_security_deposit_payment_immutable_update;
DROP TRIGGER IF EXISTS tr_security_deposit_payment_apply;
DROP TRIGGER IF EXISTS tr_security_deposit_payment_validate;
DROP TRIGGER IF EXISTS tr_payment_allocation_immutable_delete;
DROP TRIGGER IF EXISTS tr_payment_allocation_immutable_update;
DROP TRIGGER IF EXISTS tr_payment_allocation_apply;
DROP TRIGGER IF EXISTS tr_payment_allocation_validate;

DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS security_deposit_payments;
DROP TABLE IF EXISTS payment_allocations;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS rent_obligations;
DROP TABLE IF EXISTS security_deposits;
DROP TABLE IF EXISTS tenancy_assignments;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS tenants;
DROP TABLE IF EXISTS estates;

-- ============================================================================
-- Master entities
-- ============================================================================

CREATE TABLE estates (
    estate_id       INTEGER PRIMARY KEY,
    estate_code     TEXT NOT NULL UNIQUE,
    estate_name     TEXT NOT NULL UNIQUE,
    is_active       INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (estate_code = upper(trim(estate_code))),
    CHECK (estate_name = trim(estate_name))
);

CREATE TABLE units (
    unit_id                 INTEGER PRIMARY KEY,
    estate_id               INTEGER NOT NULL,
    unit_number             TEXT NOT NULL,
    listed_monthly_rent     INTEGER NOT NULL
                            CHECK (listed_monthly_rent BETWEEN 100000 AND 15000000),
    is_active               INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at              TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (estate_id)
        REFERENCES estates(estate_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    UNIQUE (estate_id, unit_number),
    CHECK (unit_number = upper(trim(unit_number))),
    CHECK (length(unit_number) >= 2)
);

CREATE TABLE tenants (
    -- Omit tenant_id from INSERT statements; SQLite generates it automatically.
    tenant_id       INTEGER PRIMARY KEY,
    tenant_type     TEXT NOT NULL DEFAULT 'INDIVIDUAL'
                    CHECK (tenant_type IN ('INDIVIDUAL', 'BUSINESS')),
    business_name   TEXT,
    first_name      TEXT NOT NULL,
    middle_name     TEXT,
    last_name       TEXT NOT NULL,
    phone_number    TEXT NOT NULL UNIQUE,
    national_id_number TEXT UNIQUE,
    alt_phone_number TEXT,
    notes           TEXT NOT NULL DEFAULT 'No notes.',
    is_active       INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (
        tenant_type <> 'BUSINESS'
        OR (business_name IS NOT NULL AND trim(business_name) <> '')
    ),
    -- Application code should perform complete Unicode-aware title-casing
    -- before insert/update. These checks protect standard ASCII name input.
    CHECK (
        first_name = trim(first_name)
        AND first_name = upper(substr(first_name, 1, 1)) || lower(substr(first_name, 2))
    ),
    CHECK (
        middle_name IS NULL
        OR (
            middle_name = trim(middle_name)
            AND middle_name = upper(substr(middle_name, 1, 1)) || lower(substr(middle_name, 2))
        )
    ),
    CHECK (
        last_name = trim(last_name)
        AND last_name = upper(substr(last_name, 1, 1)) || lower(substr(last_name, 2))
    ),

    -- Seed phone format: +256 followed by a 9-digit mobile number.
    CHECK (phone_number GLOB '+2567[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
);

-- Allows tenancy history while partial unique indexes permit only one active
-- tenancy per tenant and per unit.
CREATE TABLE tenancy_assignments (
    tenancy_id              INTEGER PRIMARY KEY,
    tenant_id               INTEGER NOT NULL,
    unit_id                 INTEGER NOT NULL,
    start_date              TEXT NOT NULL,
    end_date                TEXT,
    scheduled_move_out_date TEXT,
    agreed_monthly_rent     INTEGER NOT NULL
                            CHECK (agreed_monthly_rent BETWEEN 100000 AND 15000000),
    rent_due_day            INTEGER NOT NULL DEFAULT 5 CHECK (rent_due_day BETWEEN 1 AND 31),
    grace_period_days       INTEGER NOT NULL DEFAULT 5 CHECK (grace_period_days BETWEEN 0 AND 31),
    is_primary              INTEGER NOT NULL DEFAULT 1 CHECK (is_primary IN (0, 1)),
    created_at              TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id)
        REFERENCES tenants(tenant_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    FOREIGN KEY (unit_id)
        REFERENCES units(unit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CHECK (start_date GLOB '????-??-??'),
    CHECK (end_date IS NULL OR end_date GLOB '????-??-??'),
    CHECK (scheduled_move_out_date IS NULL OR scheduled_move_out_date GLOB '????-??-??'),
    CHECK (end_date IS NULL OR end_date >= start_date)
);

-- ============================================================================
-- Financial ledger entities
-- ============================================================================

CREATE TABLE security_deposits (
    security_deposit_id      INTEGER PRIMARY KEY,
    tenancy_id               INTEGER NOT NULL UNIQUE,
    expected_amount          INTEGER NOT NULL CHECK (expected_amount > 0),
    received_amount          INTEGER NOT NULL DEFAULT 0
                            CHECK (received_amount >= 0 AND received_amount <= expected_amount),
    status                   TEXT NOT NULL DEFAULT 'UNPAID'
                            CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID')),
    created_at               TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenancy_id)
        REFERENCES tenancy_assignments(tenancy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CHECK (
        (status = 'UNPAID' AND received_amount = 0)
        OR (status = 'PARTIAL' AND received_amount > 0 AND received_amount < expected_amount)
        OR (status = 'PAID' AND received_amount = expected_amount)
    )
);

CREATE TABLE rent_obligations (
    rent_obligation_id        INTEGER PRIMARY KEY,
    tenancy_id                INTEGER NOT NULL,
    rent_month                TEXT NOT NULL,
    due_date                  TEXT NOT NULL,
    amount_due                INTEGER NOT NULL CHECK (amount_due > 0),
    allocated_amount          INTEGER NOT NULL DEFAULT 0
                              CHECK (allocated_amount >= 0 AND allocated_amount <= amount_due),
    status                    TEXT NOT NULL DEFAULT 'UNPAID'
                              CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID')),
    created_at                TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenancy_id)
        REFERENCES tenancy_assignments(tenancy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    UNIQUE (tenancy_id, rent_month),
    CHECK (rent_month GLOB '????-??'),
    CHECK (due_date GLOB '????-??-??'),
    CHECK (
        (status = 'UNPAID' AND allocated_amount = 0)
        OR (status = 'PARTIAL' AND allocated_amount > 0 AND allocated_amount < amount_due)
        OR (status = 'PAID' AND allocated_amount = amount_due)
    )
);

CREATE TABLE payments (
    payment_id              INTEGER PRIMARY KEY,
    tenant_id               INTEGER NOT NULL,
    payment_reference       TEXT NOT NULL UNIQUE,
    payment_type            TEXT NOT NULL
                            CHECK (payment_type IN ('RENT', 'SECURITY_DEPOSIT', 'MIXED', 'ADJUSTMENT')),
    amount                  INTEGER NOT NULL CHECK (amount > 0),
    payment_date            TEXT NOT NULL,
    payment_method          TEXT NOT NULL
                            CHECK (payment_method IN ('MOBILE_MONEY', 'BANK_TRANSFER', 'CASH')),
    payment_status          TEXT NOT NULL DEFAULT 'POSTED'
                            CHECK (payment_status IN ('POSTED', 'VOIDED', 'REVERSED')),
    created_at              TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (tenant_id)
        REFERENCES tenants(tenant_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CHECK (payment_date GLOB '????-??-??')
);

CREATE TABLE payment_allocations (
    payment_allocation_id   INTEGER PRIMARY KEY,
    payment_id              INTEGER NOT NULL,
    rent_obligation_id      INTEGER NOT NULL,
    allocated_amount        INTEGER NOT NULL CHECK (allocated_amount > 0),
    created_at              TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    FOREIGN KEY (rent_obligation_id)
        REFERENCES rent_obligations(rent_obligation_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    UNIQUE (payment_id, rent_obligation_id)
);

CREATE TABLE security_deposit_payments (
    security_deposit_payment_id  INTEGER PRIMARY KEY,
    security_deposit_id          INTEGER NOT NULL,
    payment_id                   INTEGER NOT NULL UNIQUE,
    allocated_amount             INTEGER NOT NULL CHECK (allocated_amount > 0),
    created_at                   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (security_deposit_id)
        REFERENCES security_deposits(security_deposit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    UNIQUE (security_deposit_id, payment_id)
);

CREATE TABLE receipts (
    receipt_id              INTEGER PRIMARY KEY,
    payment_id              INTEGER NOT NULL UNIQUE,
    receipt_number          TEXT NOT NULL UNIQUE,
    issued_at               TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    issued_by               TEXT NOT NULL DEFAULT 'SYSTEM',

    FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CHECK (
        length(receipt_number) > 0
        AND receipt_number NOT GLOB '*[^0-9]*'
    )
);

-- ============================================================================
-- Lookup and reporting indexes
-- ============================================================================

CREATE INDEX idx_estates_name
    ON estates(estate_name);

CREATE INDEX idx_tenants_phone_number
    ON tenants(phone_number);

CREATE INDEX idx_tenancy_assignments_tenant_unit
    ON tenancy_assignments(tenant_id, unit_id, end_date);

CREATE UNIQUE INDEX ux_active_tenancy_per_tenant
    ON tenancy_assignments(tenant_id)
    WHERE end_date IS NULL;

CREATE UNIQUE INDEX ux_active_tenancy_per_unit
    ON tenancy_assignments(unit_id)
    WHERE end_date IS NULL;

CREATE INDEX idx_rent_obligations_status
    ON rent_obligations(status, due_date);

CREATE INDEX idx_payments_payment_date
    ON payments(payment_date);

CREATE INDEX idx_receipts_receipt_number
    ON receipts(receipt_number);

-- ============================================================================
-- Ledger integrity triggers
-- ============================================================================

CREATE TRIGGER tr_payment_allocation_validate
BEFORE INSERT ON payment_allocations
BEGIN
    SELECT CASE
        WHEN (SELECT payment_status FROM payments WHERE payment_id = NEW.payment_id) <> 'POSTED'
        THEN RAISE(ABORT, 'Only posted payments may be allocated to rent obligations')
    END;

    SELECT CASE
        WHEN (SELECT payment_type FROM payments WHERE payment_id = NEW.payment_id)
             NOT IN ('RENT', 'MIXED')
        THEN RAISE(ABORT, 'Only RENT or MIXED payments may be allocated to rent obligations')
    END;

    SELECT CASE
        WHEN (SELECT tenant_id FROM payments WHERE payment_id = NEW.payment_id) <>
             (
                 SELECT ta.tenant_id
                 FROM rent_obligations ro
                 JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
                 WHERE ro.rent_obligation_id = NEW.rent_obligation_id
             )
        THEN RAISE(ABORT, 'Payment tenant does not match rent obligation tenant')
    END;

    SELECT CASE
        WHEN NEW.allocated_amount >
             (
                 SELECT amount - COALESCE(
                     (
                         SELECT SUM(allocated_amount)
                         FROM payment_allocations
                         WHERE payment_id = NEW.payment_id
                     ),
                     0
                 )
                 FROM payments
                 WHERE payment_id = NEW.payment_id
             )
        THEN RAISE(ABORT, 'Payment allocation exceeds available payment balance')
    END;

    SELECT CASE
        WHEN NEW.allocated_amount >
             (
                 SELECT amount_due - allocated_amount
                 FROM rent_obligations
                 WHERE rent_obligation_id = NEW.rent_obligation_id
             )
        THEN RAISE(ABORT, 'Payment allocation exceeds outstanding rent balance')
    END;
END;

CREATE TRIGGER tr_payment_allocation_apply
AFTER INSERT ON payment_allocations
BEGIN
    UPDATE rent_obligations
    SET
        allocated_amount = (
            SELECT COALESCE(SUM(pa.allocated_amount), 0)
            FROM payment_allocations pa
            WHERE pa.rent_obligation_id = NEW.rent_obligation_id
        ),
        status = CASE
            WHEN (
                SELECT COALESCE(SUM(pa.allocated_amount), 0)
                FROM payment_allocations pa
                WHERE pa.rent_obligation_id = NEW.rent_obligation_id
            ) = 0 THEN 'UNPAID'
            WHEN (
                SELECT COALESCE(SUM(pa.allocated_amount), 0)
                FROM payment_allocations pa
                WHERE pa.rent_obligation_id = NEW.rent_obligation_id
            ) < amount_due THEN 'PARTIAL'
            ELSE 'PAID'
        END
    WHERE rent_obligation_id = NEW.rent_obligation_id;
END;

-- The allocation ledger is immutable. Correct errors using an adjustment.
CREATE TRIGGER tr_payment_allocation_immutable_update
BEFORE UPDATE ON payment_allocations
BEGIN
    SELECT RAISE(ABORT, 'Payment allocations are immutable; post an adjustment instead');
END;

CREATE TRIGGER tr_payment_allocation_immutable_delete
BEFORE DELETE ON payment_allocations
BEGIN
    SELECT RAISE(ABORT, 'Payment allocations are immutable; post an adjustment instead');
END;

CREATE TRIGGER tr_security_deposit_payment_validate
BEFORE INSERT ON security_deposit_payments
BEGIN
    SELECT CASE
        WHEN (SELECT payment_status FROM payments WHERE payment_id = NEW.payment_id) <> 'POSTED'
        THEN RAISE(ABORT, 'Only posted payments may be allocated to security deposits')
    END;

    SELECT CASE
        WHEN (SELECT payment_type FROM payments WHERE payment_id = NEW.payment_id)
             NOT IN ('SECURITY_DEPOSIT', 'MIXED')
        THEN RAISE(ABORT, 'Payment type cannot be allocated to security deposit')
    END;

    SELECT CASE
        WHEN (SELECT tenant_id FROM payments WHERE payment_id = NEW.payment_id) <>
             (
                 SELECT ta.tenant_id
                 FROM security_deposits sd
                 JOIN tenancy_assignments ta ON ta.tenancy_id = sd.tenancy_id
                 WHERE sd.security_deposit_id = NEW.security_deposit_id
             )
        THEN RAISE(ABORT, 'Payment tenant does not match security deposit tenant')
    END;

    SELECT CASE
        WHEN NEW.allocated_amount >
             (
                 SELECT amount - COALESCE(
                     (
                         SELECT SUM(allocated_amount)
                         FROM security_deposit_payments
                         WHERE payment_id = NEW.payment_id
                     ),
                     0
                 )
                 FROM payments
                 WHERE payment_id = NEW.payment_id
             )
        THEN RAISE(ABORT, 'Security deposit allocation exceeds payment balance')
    END;

    SELECT CASE
        WHEN NEW.allocated_amount >
             (
                 SELECT expected_amount - received_amount
                 FROM security_deposits
                 WHERE security_deposit_id = NEW.security_deposit_id
             )
        THEN RAISE(ABORT, 'Security deposit allocation exceeds outstanding balance')
    END;
END;

CREATE TRIGGER tr_security_deposit_payment_apply
AFTER INSERT ON security_deposit_payments
BEGIN
    UPDATE security_deposits
    SET
        received_amount = (
            SELECT COALESCE(SUM(sdp.allocated_amount), 0)
            FROM security_deposit_payments sdp
            WHERE sdp.security_deposit_id = NEW.security_deposit_id
        ),
        status = CASE
            WHEN (
                SELECT COALESCE(SUM(sdp.allocated_amount), 0)
                FROM security_deposit_payments sdp
                WHERE sdp.security_deposit_id = NEW.security_deposit_id
            ) = 0 THEN 'UNPAID'
            WHEN (
                SELECT COALESCE(SUM(sdp.allocated_amount), 0)
                FROM security_deposit_payments sdp
                WHERE sdp.security_deposit_id = NEW.security_deposit_id
            ) < expected_amount THEN 'PARTIAL'
            ELSE 'PAID'
        END
    WHERE security_deposit_id = NEW.security_deposit_id;
END;

CREATE TRIGGER tr_security_deposit_payment_immutable_update
BEFORE UPDATE ON security_deposit_payments
BEGIN
    SELECT RAISE(ABORT, 'Security deposit allocations are immutable; post an adjustment instead');
END;

CREATE TRIGGER tr_security_deposit_payment_immutable_delete
BEFORE DELETE ON security_deposit_payments
BEGIN
    SELECT RAISE(ABORT, 'Security deposit allocations are immutable; post an adjustment instead');
END;

-- ============================================================================
-- Controlled tenant input interface
-- ============================================================================
-- Use this view for ordinary inserts to normalize simple ASCII name casing.
-- Production application code should still use Unicode-aware title-case logic.

CREATE VIEW v_tenant_input AS
SELECT
    first_name,
    middle_name,
    last_name,
    phone_number,
    national_id_number,
    alt_phone_number,
    notes
FROM tenants;

CREATE TRIGGER tr_v_tenant_input_normalize_insert
INSTEAD OF INSERT ON v_tenant_input
BEGIN
    INSERT INTO tenants (
        first_name,
        middle_name,
        last_name,
        phone_number,
        national_id_number,
        alt_phone_number,
        notes
    )
    VALUES (
        upper(substr(trim(NEW.first_name), 1, 1)) || lower(substr(trim(NEW.first_name), 2)),
        CASE
            WHEN NULLIF(trim(NEW.middle_name), '') IS NULL THEN NULL
            ELSE upper(substr(trim(NEW.middle_name), 1, 1)) || lower(substr(trim(NEW.middle_name), 2))
        END,
        upper(substr(trim(NEW.last_name), 1, 1)) || lower(substr(trim(NEW.last_name), 2)),
        trim(NEW.phone_number),
        NULLIF(upper(trim(NEW.national_id_number)), ''),
        NULLIF(trim(NEW.alt_phone_number), ''),
        COALESCE(NULLIF(trim(NEW.notes), ''), 'No notes.')
    );
END;

-- ============================================================================
-- Reporting views
-- ============================================================================

CREATE VIEW v_current_tenant_directory AS
SELECT
    t.tenant_id,
    t.tenant_type,
    t.business_name,
    t.first_name,
    t.middle_name,
    t.last_name,
    CASE
        WHEN t.tenant_type = 'BUSINESS' AND trim(t.business_name) <> ''
            THEN trim(t.business_name)
        ELSE trim(t.first_name || ' ' || COALESCE(t.middle_name || ' ', '') || t.last_name)
    END AS tenant_name,
    t.phone_number,
    t.alt_phone_number,
    t.notes,
    e.estate_id,
    e.estate_name,
    u.unit_id,
    u.unit_number AS house_number,
    ta.tenancy_id,
    ta.agreed_monthly_rent AS expected_monthly_rent,
    ta.rent_due_day,
    ta.grace_period_days,
    ta.start_date,
    ta.end_date,
    ta.scheduled_move_out_date,
    sd.security_deposit_id,
    sd.status AS security_deposit_status,
    sd.expected_amount AS security_deposit_expected,
    sd.received_amount AS security_deposit_received
FROM tenants t
JOIN tenancy_assignments ta
    ON ta.tenant_id = t.tenant_id
   AND ta.end_date IS NULL
JOIN units u
    ON u.unit_id = ta.unit_id
JOIN estates e
    ON e.estate_id = u.estate_id
JOIN security_deposits sd
    ON sd.tenancy_id = ta.tenancy_id;

CREATE VIEW v_tenant_account_status AS
SELECT
    d.*,
    COALESCE((
        SELECT COUNT(*)
        FROM rent_obligations ro
        JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
        WHERE ta.tenant_id = d.tenant_id
          AND ta.end_date IS NULL
          AND ro.rent_month <= strftime('%Y-%m', 'now')
          AND ro.status <> 'PAID'
    ), 0) AS pending_months_owed,
    COALESCE((
        SELECT SUM(ro.amount_due - ro.allocated_amount)
        FROM rent_obligations ro
        JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
        WHERE ta.tenant_id = d.tenant_id
          AND ta.end_date IS NULL
          AND ro.rent_month <= strftime('%Y-%m', 'now')
    ), 0) AS rent_outstanding_balance,
    d.security_deposit_expected - d.security_deposit_received AS security_deposit_balance,
    CASE
        WHEN d.security_deposit_status <> 'PAID'
             AND COALESCE((
                 SELECT COUNT(*)
                 FROM rent_obligations ro
                 JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
                 WHERE ta.tenant_id = d.tenant_id
                   AND ta.end_date IS NULL
                   AND ro.rent_month <= strftime('%Y-%m', 'now')
                   AND ro.status <> 'PAID'
             ), 0) = 0
        THEN 'MISSING_SECURITY_DEPOSIT'

        WHEN COALESCE((
            SELECT COUNT(*)
            FROM rent_obligations ro
            JOIN tenancy_assignments ta ON ta.tenancy_id = ro.tenancy_id
            WHERE ta.tenant_id = d.tenant_id
              AND ta.end_date IS NULL
              AND ro.rent_month <= strftime('%Y-%m', 'now')
              AND ro.status <> 'PAID'
        ), 0) > 0
        THEN 'IN_ARREARS'

        WHEN d.start_date >= date('now', '-90 days')
        THEN 'NEW_MOVE_IN_CLEAN'

        ELSE 'FULLY_PAID_UP'
    END AS account_category
FROM v_current_tenant_directory d;

-- ============================================================================
-- Estate and unit seed data
-- ============================================================================

INSERT INTO estates (estate_code, estate_name) VALUES
    ('KIB', 'Kibby'),
    ('NAN', 'Nancy'),
    ('MOR', 'Moriah'),
    ('EBI', 'Ebenezer'),
    ('GAS', 'Gashy'),
    ('TIN', 'Ntinda'),
    ('CHI', 'Chibi');

-- 100 units: 15 + 15 + 14 + 14 + 14 + 14 + 14.
-- Unit numbers are unique per estate: A1-A8 and B1-B7 where required.
WITH RECURSIVE
estate_capacity(estate_name, max_units) AS (
    VALUES
        ('Kibby', 15),
        ('Nancy', 15),
        ('Moriah', 14),
        ('Ebenezer', 14),
        ('Gashy', 14),
        ('Ntinda', 14),
        ('Chibi', 14)
),
series(estate_name, max_units, unit_sequence) AS (
    SELECT estate_name, max_units, 1
    FROM estate_capacity
    UNION ALL
    SELECT estate_name, max_units, unit_sequence + 1
    FROM series
    WHERE unit_sequence < max_units
)
INSERT INTO units (estate_id, unit_number, listed_monthly_rent)
SELECT
    e.estate_id,
    char(65 + CAST((s.unit_sequence - 1) / 8 AS INTEGER))
        || CAST(((s.unit_sequence - 1) % 8) + 1 AS TEXT),
    CASE ((s.unit_sequence - 1) % 12)
        WHEN 0 THEN 300000
        WHEN 1 THEN 350000
        WHEN 2 THEN 450000
        WHEN 3 THEN 550000
        WHEN 4 THEN 650000
        WHEN 5 THEN 800000
        WHEN 6 THEN 950000
        WHEN 7 THEN 1200000
        WHEN 8 THEN 1500000
        WHEN 9 THEN 1800000
        WHEN 10 THEN 2500000
        ELSE 3500000
    END
FROM series s
JOIN estates e
    ON e.estate_name = s.estate_name;

-- ============================================================================
-- 108 tenant records. tenant_id values are generated by SQLite.
-- The fresh seed creates tenant IDs 1-100 for current renters and 101-108 for
-- former renters, used below only to create deterministic seed cohorts; IDs
-- are never inserted manually.
--   1-30: fully paid up
--   31-60: in arrears
--   61-80: new move-ins, clean
--   81-100: current on rent, security deposit missing
--   101-108: former renters with closed tenancy history
-- ============================================================================

INSERT INTO tenants (first_name, middle_name, last_name, phone_number) VALUES
    ('Amina', NULL, 'Kato', '+256700555001'),
    ('Brian', 'David', 'Ssemanda', '+256700555002'),
    ('Clare', NULL, 'Nansubuga', '+256700555003'),
    ('Daniel', 'Paul', 'Okello', '+256700555004'),
    ('Esther', NULL, 'Nakato', '+256700555005'),
    ('Felix', 'John', 'Mugisha', '+256700555006'),
    ('Grace', NULL, 'Namutebi', '+256700555007'),
    ('Hassan', 'Ali', 'Kiggundu', '+256700555008'),
    ('Irene', NULL, 'Atwine', '+256700555009'),
    ('Joel', 'Mark', 'Ssekandi', '+256700555010'),
    ('Karen', NULL, 'Akello', '+256700555011'),
    ('Lucas', 'Peter', 'Ouma', '+256700555012'),
    ('Mariam', NULL, 'Nabirye', '+256700555013'),
    ('Nathan', 'Isaac', 'Sserwanga', '+256700555014'),
    ('Olivia', NULL, 'Adoch', '+256700555015'),
    ('Patrick', 'James', 'Kato', '+256700555016'),
    ('Queen', NULL, 'Nambi', '+256700555017'),
    ('Ronald', 'David', 'Ocen', '+256700555018'),
    ('Sarah', NULL, 'Namusoke', '+256700555019'),
    ('Timothy', 'Allan', 'Opio', '+256700555020'),
    ('Vivian', NULL, 'Nakibuuka', '+256700555021'),
    ('Walter', 'Moses', 'Kato', '+256700555022'),
    ('Xenia', NULL, 'Auma', '+256700555023'),
    ('Yusuf', 'Hamza', 'Ssebuufu', '+256700555024'),
    ('Zawadi', NULL, 'Nankya', '+256700555025'),
    ('Andrew', 'Brian', 'Lumu', '+256700555026'),
    ('Beatrice', NULL, 'Kemigisha', '+256700555027'),
    ('Collins', 'Peter', 'Mukiibi', '+256700555028'),
    ('Diana', NULL, 'Akankwasa', '+256700555029'),
    ('Edward', 'Simon', 'Waiswa', '+256700555030'),
    ('Faith', NULL, 'Nambalirwa', '+256700555031'),
    ('George', 'Allan', 'Mwesigwa', '+256700555032'),
    ('Halima', NULL, 'Nankabirwa', '+256700555033'),
    ('Isaac', 'Joel', 'Tumusiime', '+256700555034'),
    ('Janet', NULL, 'Akello', '+256700555035'),
    ('Kevin', 'Mark', 'Ssemanda', '+256700555036'),
    ('Lydia', NULL, 'Nakayiza', '+256700555037'),
    ('Moses', 'Daniel', 'Kato', '+256700555038'),
    ('Nadia', NULL, 'Atuhairwe', '+256700555039'),
    ('Owen', 'Patrick', 'Ouma', '+256700555040'),
    ('Precious', NULL, 'Nanziri', '+256700555041'),
    ('Robert', 'John', 'Mugabi', '+256700555042'),
    ('Sharon', NULL, 'Namirembe', '+256700555043'),
    ('Thomas', 'Allan', 'Ocen', '+256700555044'),
    ('Ursula', NULL, 'Nakintu', '+256700555045'),
    ('Victor', 'Paul', 'Ssempa', '+256700555046'),
    ('Winnie', NULL, 'Aciro', '+256700555047'),
    ('Xavier', 'Mark', 'Kato', '+256700555048'),
    ('Yvonne', NULL, 'Nansamba', '+256700555049'),
    ('Zubair', 'Ali', 'Mugisha', '+256700555050'),
    ('Angela', NULL, 'Nakitende', '+256700555051'),
    ('Benson', 'David', 'Lule', '+256700555052'),
    ('Charity', NULL, 'Nanyonga', '+256700555053'),
    ('Derrick', 'John', 'Okot', '+256700555054'),
    ('Eunice', NULL, 'Kemunto', '+256700555055'),
    ('Francis', 'Paul', 'Kintu', '+256700555056'),
    ('Gloria', NULL, 'Namara', '+256700555057'),
    ('Henry', 'Mark', 'Ssekitoleko', '+256700555058'),
    ('Immaculate', NULL, 'Aciro', '+256700555059'),
    ('Jacob', 'Peter', 'Mukiibi', '+256700555060'),
    ('Kira', NULL, 'Nambassa', '+256700555061'),
    ('Lawrence', 'David', 'Otema', '+256700555062'),
    ('Monica', NULL, 'Nakitto', '+256700555063'),
    ('Nelson', 'John', 'Ssemanda', '+256700555064'),
    ('Penelope', NULL, 'Auma', '+256700555065'),
    ('Quincy', 'Mark', 'Okello', '+256700555066'),
    ('Rebecca', NULL, 'Nansubuga', '+256700555067'),
    ('Samuel', 'Paul', 'Kato', '+256700555068'),
    ('Tabitha', NULL, 'Namutebi', '+256700555069'),
    ('Umar', 'Ali', 'Kiggundu', '+256700555070'),
    ('Vanessa', NULL, 'Atwine', '+256700555071'),
    ('Wilfred', 'John', 'Ssekandi', '+256700555072'),
    ('Yasmin', NULL, 'Akello', '+256700555073'),
    ('Zachary', 'Peter', 'Ouma', '+256700555074'),
    ('Alice', NULL, 'Nabirye', '+256700555075'),
    ('Bernard', 'Isaac', 'Sserwanga', '+256700555076'),
    ('Cecilia', NULL, 'Adoch', '+256700555077'),
    ('Dominic', 'James', 'Kato', '+256700555078'),
    ('Elisha', NULL, 'Nambi', '+256700555079'),
    ('Farid', 'David', 'Ocen', '+256700555080'),
    ('Gertrude', NULL, 'Namusoke', '+256700555081'),
    ('Howard', 'Allan', 'Opio', '+256700555082'),
    ('Ivy', NULL, 'Nakibuuka', '+256700555083'),
    ('Joshua', 'Moses', 'Kato', '+256700555084'),
    ('Kellen', NULL, 'Auma', '+256700555085'),
    ('Leonard', 'Hamza', 'Ssebuufu', '+256700555086'),
    ('Mercy', NULL, 'Nankya', '+256700555087'),
    ('Noah', 'Brian', 'Lumu', '+256700555088'),
    ('Phoebe', NULL, 'Kemigisha', '+256700555089'),
    ('Raymond', 'Peter', 'Mukiibi', '+256700555090'),
    ('Stella', NULL, 'Akankwasa', '+256700555091'),
    ('Trevor', 'Simon', 'Waiswa', '+256700555092'),
    ('Unity', NULL, 'Nambalirwa', '+256700555093'),
    ('Vincent', 'Allan', 'Mwesigwa', '+256700555094'),
    ('Winifred', NULL, 'Nankabirwa', '+256700555095'),
    ('Xavier', 'Joel', 'Tumusiime', '+256700555096'),
    ('Yvette', NULL, 'Akello', '+256700555097'),
    ('Zaina', 'Mark', 'Ssemanda', '+256700555098'),
    ('Arthur', NULL, 'Nakayiza', '+256700555099'),
    ('Brenda', 'Daniel', 'Kato', '+256700555100');

-- Assign every generated tenant ID to one valid estate and one unique unit.
WITH assigned_tenants AS (
    SELECT
        t.tenant_id,
        CASE
            WHEN t.tenant_id BETWEEN 1 AND 15 THEN 'Kibby'
            WHEN t.tenant_id BETWEEN 16 AND 30 THEN 'Nancy'
            WHEN t.tenant_id BETWEEN 31 AND 44 THEN 'Moriah'
            WHEN t.tenant_id BETWEEN 45 AND 58 THEN 'Ebenezer'
            WHEN t.tenant_id BETWEEN 59 AND 72 THEN 'Gashy'
            WHEN t.tenant_id BETWEEN 73 AND 86 THEN 'Ntinda'
            ELSE 'Chibi'
        END AS estate_name,
        CASE
            WHEN t.tenant_id BETWEEN 1 AND 15 THEN t.tenant_id
            WHEN t.tenant_id BETWEEN 16 AND 30 THEN t.tenant_id - 15
            WHEN t.tenant_id BETWEEN 31 AND 44 THEN t.tenant_id - 30
            WHEN t.tenant_id BETWEEN 45 AND 58 THEN t.tenant_id - 44
            WHEN t.tenant_id BETWEEN 59 AND 72 THEN t.tenant_id - 58
            WHEN t.tenant_id BETWEEN 73 AND 86 THEN t.tenant_id - 72
            ELSE t.tenant_id - 86
        END AS unit_sequence
    FROM tenants t
)
INSERT INTO tenancy_assignments (
    tenant_id,
    unit_id,
    start_date,
    agreed_monthly_rent
)
SELECT
    at.tenant_id,
    u.unit_id,
    CASE
        WHEN at.tenant_id BETWEEN 1 AND 30
            THEN date('2024-06-01', '+' || (at.tenant_id - 1) || ' days')
        WHEN at.tenant_id BETWEEN 31 AND 60
            THEN date('2024-01-01', '+' || (at.tenant_id - 31) || ' days')
        WHEN at.tenant_id BETWEEN 61 AND 80
            THEN date('2026-05-01', '+' || (at.tenant_id - 61) || ' days')
        ELSE date('2024-09-01', '+' || (at.tenant_id - 81) || ' days')
    END,
    u.listed_monthly_rent
FROM assigned_tenants at
JOIN estates e
    ON e.estate_name = at.estate_name
JOIN units u
    ON u.estate_id = e.estate_id
   AND u.unit_number =
        char(65 + CAST((at.unit_sequence - 1) / 8 AS INTEGER))
        || CAST(((at.unit_sequence - 1) % 8) + 1 AS TEXT);

-- Every tenancy receives a security deposit requirement equal to one month's rent.
INSERT INTO security_deposits (tenancy_id, expected_amount)
SELECT tenancy_id, agreed_monthly_rent
FROM tenancy_assignments;

-- Arrears tenants receive January-June obligations. The other cohorts receive
-- only the applicable current months.
WITH
month_seed(month_order, rent_month, due_date) AS (
    VALUES
        (1, '2026-01', '2026-01-05'),
        (2, '2026-02', '2026-02-05'),
        (3, '2026-03', '2026-03-05'),
        (4, '2026-04', '2026-04-05'),
        (5, '2026-05', '2026-05-05'),
        (6, '2026-06', '2026-06-05')
)
INSERT INTO rent_obligations (
    tenancy_id,
    rent_month,
    due_date,
    amount_due
)
SELECT
    ta.tenancy_id,
    ms.rent_month,
    ms.due_date,
    ta.agreed_monthly_rent
FROM tenancy_assignments ta
JOIN month_seed ms
WHERE
    ta.tenant_id BETWEEN 31 AND 60
    OR (ta.tenant_id BETWEEN 1 AND 30 AND ms.month_order BETWEEN 4 AND 6)
    OR (ta.tenant_id BETWEEN 61 AND 80 AND ms.month_order = 6)
    OR (ta.tenant_id BETWEEN 81 AND 100 AND ms.month_order BETWEEN 4 AND 6);

-- Tenants 1-80 pay their deposits. Tenants 81-100 deliberately have unpaid
-- deposits while remaining current on rent.
INSERT INTO payments (
    tenant_id,
    payment_reference,
    payment_type,
    amount,
    payment_date,
    payment_method
)
SELECT
    ta.tenant_id,
    'SEC-' || printf('%06d', ta.tenant_id),
    'SECURITY_DEPOSIT',
    sd.expected_amount,
    date(ta.start_date, '+1 day'),
    CASE ta.tenant_id % 3
        WHEN 0 THEN 'MOBILE_MONEY'
        WHEN 1 THEN 'BANK_TRANSFER'
        ELSE 'CASH'
    END
FROM tenancy_assignments ta
JOIN security_deposits sd
    ON sd.tenancy_id = ta.tenancy_id
WHERE ta.tenant_id BETWEEN 1 AND 80;

INSERT INTO security_deposit_payments (
    security_deposit_id,
    payment_id,
    allocated_amount
)
SELECT
    sd.security_deposit_id,
    p.payment_id,
    sd.expected_amount
FROM tenancy_assignments ta
JOIN security_deposits sd
    ON sd.tenancy_id = ta.tenancy_id
JOIN payments p
    ON p.payment_reference = 'SEC-' || printf('%06d', ta.tenant_id)
WHERE ta.tenant_id BETWEEN 1 AND 80;

-- Create one rent payment per tenant. Its allocations cover all paid months.
-- For arrears tenants, the final 1-4 months remain unpaid.
WITH paid_obligations AS (
    SELECT
        ta.tenant_id,
        SUM(ro.amount_due) AS payment_amount,
        date(MAX(ro.due_date), '+1 day') AS payment_date
    FROM tenancy_assignments ta
JOIN rent_obligations ro
    ON ro.tenancy_id = ta.tenancy_id
    WHERE
        ta.tenant_id NOT BETWEEN 31 AND 60
        OR ro.rent_month <= printf(
            '2026-%02d',
            6 - (((ta.tenant_id - 31) % 4) + 1)
        )
    GROUP BY ta.tenant_id
)
INSERT INTO payments (
    tenant_id,
    payment_reference,
    payment_type,
    amount,
    payment_date,
    payment_method
)
SELECT
    tenant_id,
    'RENT-' || printf('%06d', tenant_id),
    'RENT',
    payment_amount,
    payment_date,
    CASE tenant_id % 3
        WHEN 0 THEN 'MOBILE_MONEY'
        WHEN 1 THEN 'BANK_TRANSFER'
        ELSE 'CASH'
    END
FROM paid_obligations;

INSERT INTO payment_allocations (
    payment_id,
    rent_obligation_id,
    allocated_amount
)
SELECT
    p.payment_id,
    ro.rent_obligation_id,
    ro.amount_due
FROM tenancy_assignments ta
JOIN rent_obligations ro
    ON ro.tenancy_id = ta.tenancy_id
JOIN payments p
    ON p.payment_reference = 'RENT-' || printf('%06d', ta.tenant_id)
WHERE
    ta.tenant_id NOT BETWEEN 31 AND 60
    OR ro.rent_month <= printf(
        '2026-%02d',
        6 - (((ta.tenant_id - 31) % 4) + 1)
    );

-- Each posted payment receives one receipt. No SMS feature is included.
INSERT INTO receipts (
    payment_id,
    receipt_number,
    issued_at,
    issued_by
)
SELECT
    p.payment_id,
    printf('%06d', p.payment_id),
    p.payment_date || 'T09:00:00',
    'SYSTEM'
FROM payments p
WHERE p.payment_status = 'POSTED';

-- ============================================================================
-- Former renters with closed tenancy history
-- ============================================================================

INSERT INTO tenants (
    first_name,
    middle_name,
    last_name,
    phone_number,
    is_active
) VALUES
    ('Ruth', NULL, 'Nakyeyune', '+256700555101', 0),
    ('Martin', 'Joseph', 'Kibirige', '+256700555102', 0),
    ('Prossy', NULL, 'Nanteza', '+256700555103', 0),
    ('Simon', 'Peter', 'Wamala', '+256700555104', 0),
    ('Agnes', NULL, 'Nakiranda', '+256700555105', 0),
    ('Julius', 'David', 'Muwonge', '+256700555106', 0),
    ('Ritah', NULL, 'Akol', '+256700555107', 0),
    ('Peter', 'Samuel', 'Ssenyonga', '+256700555108', 0);

WITH former_tenancy_seed(
    phone_number,
    estate_name,
    unit_number,
    start_date,
    end_date
) AS (
    VALUES
        ('+256700555101', 'Kibby', 'A1', '2023-02-01', '2025-01-31'),
        ('+256700555102', 'Nancy', 'A3', '2023-05-15', '2025-02-28'),
        ('+256700555103', 'Moriah', 'A5', '2023-07-01', '2025-03-31'),
        ('+256700555104', 'Ebenezer', 'B1', '2023-09-20', '2025-04-30'),
        ('+256700555105', 'Gashy', 'A2', '2024-01-10', '2025-05-31'),
        ('+256700555106', 'Ntinda', 'A6', '2024-02-01', '2025-06-30'),
        ('+256700555107', 'Chibi', 'B3', '2024-03-15', '2025-06-30'),
        ('+256700555108', 'Kibby', 'B4', '2024-04-01', '2025-06-30')
)
INSERT INTO tenancy_assignments (
    tenant_id,
    unit_id,
    start_date,
    end_date,
    agreed_monthly_rent
)
SELECT
    t.tenant_id,
    u.unit_id,
    fts.start_date,
    fts.end_date,
    u.listed_monthly_rent
FROM former_tenancy_seed fts
JOIN tenants t
    ON t.phone_number = fts.phone_number
JOIN estates e
    ON e.estate_name = fts.estate_name
JOIN units u
    ON u.estate_id = e.estate_id
   AND u.unit_number = fts.unit_number;

WITH former_tenants(phone_number) AS (
    VALUES
        ('+256700555101'),
        ('+256700555102'),
        ('+256700555103'),
        ('+256700555104'),
        ('+256700555105'),
        ('+256700555106'),
        ('+256700555107'),
        ('+256700555108')
)
INSERT INTO security_deposits (tenancy_id, expected_amount)
SELECT
    ta.tenancy_id,
    ta.agreed_monthly_rent
FROM tenancy_assignments ta
JOIN tenants t
    ON t.tenant_id = ta.tenant_id
JOIN former_tenants ft
    ON ft.phone_number = t.phone_number;

WITH
former_tenants(phone_number) AS (
    VALUES
        ('+256700555101'),
        ('+256700555102'),
        ('+256700555103'),
        ('+256700555104'),
        ('+256700555105'),
        ('+256700555106'),
        ('+256700555107'),
        ('+256700555108')
),
month_seed(month_order, rent_month, due_date) AS (
    VALUES
        (1, '2025-01', '2025-01-05'),
        (2, '2025-02', '2025-02-05'),
        (3, '2025-03', '2025-03-05'),
        (4, '2025-04', '2025-04-05'),
        (5, '2025-05', '2025-05-05'),
        (6, '2025-06', '2025-06-05')
)
INSERT INTO rent_obligations (
    tenancy_id,
    rent_month,
    due_date,
    amount_due
)
SELECT
    ta.tenancy_id,
    ms.rent_month,
    ms.due_date,
    ta.agreed_monthly_rent
FROM tenancy_assignments ta
JOIN tenants t
    ON t.tenant_id = ta.tenant_id
JOIN former_tenants ft
    ON ft.phone_number = t.phone_number
JOIN month_seed ms
    ON ms.rent_month BETWEEN substr(ta.start_date, 1, 7)
                         AND substr(ta.end_date, 1, 7);

WITH former_tenants(phone_number) AS (
    VALUES
        ('+256700555101'),
        ('+256700555102'),
        ('+256700555103'),
        ('+256700555104'),
        ('+256700555105'),
        ('+256700555106'),
        ('+256700555107'),
        ('+256700555108')
)
INSERT INTO payments (
    tenant_id,
    payment_reference,
    payment_type,
    amount,
    payment_date,
    payment_method
)
SELECT
    ta.tenant_id,
    'VAC-SEC-' || printf('%06d', ta.tenant_id),
    'SECURITY_DEPOSIT',
    sd.expected_amount,
    date(ta.start_date, '+1 day'),
    CASE ta.tenant_id % 3
        WHEN 0 THEN 'MOBILE_MONEY'
        WHEN 1 THEN 'BANK_TRANSFER'
        ELSE 'CASH'
    END
FROM tenancy_assignments ta
JOIN tenants t
    ON t.tenant_id = ta.tenant_id
JOIN former_tenants ft
    ON ft.phone_number = t.phone_number
JOIN security_deposits sd
    ON sd.tenancy_id = ta.tenancy_id;

WITH former_tenants(phone_number) AS (
    VALUES
        ('+256700555101'),
        ('+256700555102'),
        ('+256700555103'),
        ('+256700555104'),
        ('+256700555105'),
        ('+256700555106'),
        ('+256700555107'),
        ('+256700555108')
)
INSERT INTO security_deposit_payments (
    security_deposit_id,
    payment_id,
    allocated_amount
)
SELECT
    sd.security_deposit_id,
    p.payment_id,
    sd.expected_amount
FROM tenancy_assignments ta
JOIN tenants t
    ON t.tenant_id = ta.tenant_id
JOIN former_tenants ft
    ON ft.phone_number = t.phone_number
JOIN security_deposits sd
    ON sd.tenancy_id = ta.tenancy_id
JOIN payments p
    ON p.payment_reference = 'VAC-SEC-' || printf('%06d', ta.tenant_id);

WITH
former_tenants(phone_number) AS (
    VALUES
        ('+256700555101'),
        ('+256700555102'),
        ('+256700555103'),
        ('+256700555104'),
        ('+256700555105'),
        ('+256700555106'),
        ('+256700555107'),
        ('+256700555108')
),
former_paid_obligations AS (
    SELECT
        ta.tenant_id,
        SUM(ro.amount_due) AS payment_amount,
        date(MAX(ro.due_date), '+1 day') AS payment_date
    FROM tenancy_assignments ta
    JOIN tenants t
        ON t.tenant_id = ta.tenant_id
    JOIN former_tenants ft
        ON ft.phone_number = t.phone_number
    JOIN rent_obligations ro
        ON ro.tenancy_id = ta.tenancy_id
    GROUP BY ta.tenant_id
)
INSERT INTO payments (
    tenant_id,
    payment_reference,
    payment_type,
    amount,
    payment_date,
    payment_method
)
SELECT
    tenant_id,
    'VAC-RENT-' || printf('%06d', tenant_id),
    'RENT',
    payment_amount,
    payment_date,
    CASE tenant_id % 3
        WHEN 0 THEN 'MOBILE_MONEY'
        WHEN 1 THEN 'BANK_TRANSFER'
        ELSE 'CASH'
    END
FROM former_paid_obligations;

WITH former_tenants(phone_number) AS (
    VALUES
        ('+256700555101'),
        ('+256700555102'),
        ('+256700555103'),
        ('+256700555104'),
        ('+256700555105'),
        ('+256700555106'),
        ('+256700555107'),
        ('+256700555108')
)
INSERT INTO payment_allocations (
    payment_id,
    rent_obligation_id,
    allocated_amount
)
SELECT
    p.payment_id,
    ro.rent_obligation_id,
    ro.amount_due
FROM tenancy_assignments ta
JOIN tenants t
    ON t.tenant_id = ta.tenant_id
JOIN former_tenants ft
    ON ft.phone_number = t.phone_number
JOIN rent_obligations ro
    ON ro.tenancy_id = ta.tenancy_id
JOIN payments p
    ON p.payment_reference = 'VAC-RENT-' || printf('%06d', ta.tenant_id);

INSERT INTO receipts (
    payment_id,
    receipt_number,
    issued_at,
    issued_by
)
SELECT
    p.payment_id,
    printf('%06d', p.payment_id),
    p.payment_date || 'T09:00:00',
    'SYSTEM'
FROM payments p
WHERE p.payment_status = 'POSTED'
  AND p.payment_reference GLOB 'VAC-*';

-- Optional post-seed verification queries:
-- SELECT account_category, COUNT(*)
-- FROM v_tenant_account_status
-- GROUP BY account_category;
--
-- SELECT pending_months_owed, COUNT(*)
-- FROM v_tenant_account_status
-- WHERE account_category = 'IN_ARREARS'
-- GROUP BY pending_months_owed;
